//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuadrotorDesigner.Workspace.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuadrotorDesigner.Workspace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\Assembly\ 的本地化字符串。
        /// </summary>
        internal static string AssemblyPath {
            get {
                return ResourceManager.GetString("AssemblyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\Battery\ 的本地化字符串。
        /// </summary>
        internal static string BatteryModelPath {
            get {
                return ResourceManager.GetString("BatteryModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg_load {
            get {
                object obj = ResourceManager.GetObject("bg_load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\Body\ 的本地化字符串。
        /// </summary>
        internal static string BodyModelPath {
            get {
                return ResourceManager.GetString("BodyModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap component_docking_icon {
            get {
                object obj = ResourceManager.GetObject("component_docking_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap component_file {
            get {
                object obj = ResourceManager.GetObject("component_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap component_selected {
            get {
                object obj = ResourceManager.GetObject("component_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Body|Motor|ESC|Battery|Propeller|Device|RC|Flight Controller 的本地化字符串。
        /// </summary>
        internal static string ComponentsTypeList {
            get {
                return ResourceManager.GetString("ComponentsTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap console_docking_icon {
            get {
                object obj = ResourceManager.GetObject("console_docking_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy_icon {
            get {
                object obj = ResourceManager.GetObject("copy_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cut_icon {
            get {
                object obj = ResourceManager.GetObject("cut_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap delete_icon {
            get {
                object obj = ResourceManager.GetObject("delete_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap design_icon {
            get {
                object obj = ResourceManager.GetObject("design_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 .assembly 的本地化字符串。
        /// </summary>
        internal static string DesignFileExtName {
            get {
                return ResourceManager.GetString("DesignFileExtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\Device\ 的本地化字符串。
        /// </summary>
        internal static string DeviceModelPath {
            get {
                return ResourceManager.GetString("DeviceModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Config\Layout.json 的本地化字符串。
        /// </summary>
        internal static string DockConfigFile {
            get {
                return ResourceManager.GetString("DockConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap document_icon {
            get {
                object obj = ResourceManager.GetObject("document_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap exit_icon {
            get {
                object obj = ResourceManager.GetObject("exit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap find_icon {
            get {
                object obj = ResourceManager.GetObject("find_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\FlightController\ 的本地化字符串。
        /// </summary>
        internal static string FlightControllerModelPath {
            get {
                return ResourceManager.GetString("FlightControllerModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder_closed {
            get {
                object obj = ResourceManager.GetObject("folder_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap goto_line_icon {
            get {
                object obj = ResourceManager.GetObject("goto_line_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap info_icon {
            get {
                object obj = ResourceManager.GetObject("info_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string LoadSplashDelay {
            get {
                return ResourceManager.GetString("LoadSplashDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .model 的本地化字符串。
        /// </summary>
        internal static string ModelFileExtName {
            get {
                return ResourceManager.GetString("ModelFileExtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\Motor\ 的本地化字符串。
        /// </summary>
        internal static string MotorModelPath {
            get {
                return ResourceManager.GetString("MotorModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap new_icon {
            get {
                object obj = ResourceManager.GetObject("new_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap paste_icon {
            get {
                object obj = ResourceManager.GetObject("paste_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.jpg|{0}.png|{0}.bmp 的本地化字符串。
        /// </summary>
        internal static string PreviewImageFileName {
            get {
                return ResourceManager.GetString("PreviewImageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\Propeller\ 的本地化字符串。
        /// </summary>
        internal static string PropellerModelPath {
            get {
                return ResourceManager.GetString("PropellerModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap properties_docking_icon {
            get {
                object obj = ResourceManager.GetObject("properties_docking_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap redo_icon {
            get {
                object obj = ResourceManager.GetObject("redo_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\Remote\ 的本地化字符串。
        /// </summary>
        internal static string RemoteModelPath {
            get {
                return ResourceManager.GetString("RemoteModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap replace_icon {
            get {
                object obj = ResourceManager.GetObject("replace_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap run_icon {
            get {
                object obj = ResourceManager.GetObject("run_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save_all_icon {
            get {
                object obj = ResourceManager.GetObject("save_all_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save_as_icon {
            get {
                object obj = ResourceManager.GetObject("save_as_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save_icon {
            get {
                object obj = ResourceManager.GetObject("save_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 \Models\SpeedController\ 的本地化字符串。
        /// </summary>
        internal static string SpeedControllerModelPath {
            get {
                return ResourceManager.GetString("SpeedControllerModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 | 的本地化字符串。
        /// </summary>
        internal static string SplitChar {
            get {
                return ResourceManager.GetString("SplitChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _template 的本地化字符串。
        /// </summary>
        internal static string TemplateFileName {
            get {
                return ResourceManager.GetString("TemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [R/W] 的本地化字符串。
        /// </summary>
        internal static string TitleEditable {
            get {
                return ResourceManager.GetString("TitleEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quadrotor Designer 的本地化字符串。
        /// </summary>
        internal static string TitleNormal {
            get {
                return ResourceManager.GetString("TitleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [R] 的本地化字符串。
        /// </summary>
        internal static string TitleReadonly {
            get {
                return ResourceManager.GetString("TitleReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap undo_icon {
            get {
                object obj = ResourceManager.GetObject("undo_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap web_page_icon {
            get {
                object obj = ResourceManager.GetObject("web_page_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
